# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35cc77718ecfd526a6c3a2afbc9d496ea0e05f50cd622c08d3564584700df29be32e7c3361a43d3f5b3fa869a43361fd1d3013c8343ed20301bdc42ad2e32a00

test:
  secret_key_base: 015f515951b013bf96d5c19ca54e3026b81fc4be72bfd3c744b5784691c86f06d265666732fdaa00609b82a6ebf111efa87b39e86b2f600257e13e6703795e00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
